language: java
before_install:
  - echo "127.0.0.1 "`hostname` | sudo tee /etc/hosts
after_script:
  - "[[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_JDK_VERSION == oraclejdk8 ]] && [[ $TRAVIS_BRANCH == master ]] && mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.host.url=https://nemo.sonarqube.org -Dsonar.login=${SONAR_TOKEN}"
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
